# Generated by Django 4.2.2 on 2023-06-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
